r

diff --git a/0x05-processes_and_signals/100-process_and_pid_file b/0x05-processes_and_signals/100-process_and_pid_file
--- a/0x05-processes_and_signals/100-process_and_pid_file
+++ b/0x05-processes_and_signals/100-process_and_pid_file
@@ -5,20 +5,42 @@
 #   Displays "I hate the kill command" upon receiving a SIGTERM
 #   Displays "Y U no love me?!" upon receiving a SIGINT
 #   Deletes the file /var/run/mycript.pid and terminates upon
-#+  receiving a SIGQUIT or SIGTERM.
+#+  receiving a SIGQUIT or SIGTERM signal
 
-terminator() {
-  rm /var/run/myscript.pid
-  exit
+# Create the PID file
+pidfile="/var/run/myscript.pid"
+echo $$ > "$pidfile"
+
+# Function to handle SIGTERM
+handle_sigterm() {
+  echo "I hate the kill command"
+  cleanup_and_exit
 }
 
-echo "$$" > /var/run/myscript.pid
+# Function to handle SIGINT
+handle_sigint() {
+  echo "Y U no love me?!"
+}
 
-while true
-do
+# Function to handle SIGQUIT
+handle_sigquit() {
+  cleanup_and_exit
+}
+
+# Function to clean up and exit
+cleanup_and_exit() {
+  echo "Cleaning up and exiting..."
+  rm -f "$pidfile"
+  exit 0
+}
+
+# Trap signals
+trap handle_sigterm SIGTERM
+trap handle_sigint SIGINT
+trap handle_sigquit SIGQUIT
+
+# Infinite loop to display "To infinity and beyond"
+while true; do
   echo "To infinity and beyond"
   sleep 2
-  trap 'echo "Y U no love me?!"' SIGINT
-  trap 'echo "I hate the kill command" && terminator' SIGTERM
-  trap 'terminator' SIGQUIT
 done
